// <auto-generated />
using System;
using Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace pr_3._4.Migrations
{
    [DbContext(typeof(HairSalonContext))]
    [Migration("20260422155001_Final5")]
    partial class Final5
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.26")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Models.Master", b =>
                {
                    b.Property<int>("MasterId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MasterId"));

                    b.Property<string>("Description")
                        .HasMaxLength(1500)
                        .HasColumnType("nvarchar(1500)")
                        .HasColumnName("Описание");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Адрес почты");

                    b.Property<string>("Experience")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Опыт");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("Имя");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)")
                        .HasColumnName("Пол");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("Фамилия");

                    b.HasKey("MasterId");

                    b.ToTable("Masters");

                    b.HasData(
                        new
                        {
                            MasterId = 1,
                            Description = "по умолчанию 1",
                            Email = "YGGDRASIL@gmail.com",
                            Experience = "100 Лет",
                            FirstName = "Сатору",
                            Gender = "М",
                            LastName = "Судзуки"
                        },
                        new
                        {
                            MasterId = 2,
                            Description = "по умолчанию 2",
                            Email = "Overlord@gmail.com",
                            Experience = "100 Лет",
                            FirstName = "Айнз",
                            Gender = "М",
                            LastName = "ОалГоун"
                        },
                        new
                        {
                            MasterId = 3,
                            Description = "по умолчанию 3",
                            Email = "Degurechaff@gmail.com",
                            Experience = "100 Лет",
                            FirstName = "Таня",
                            Gender = "Ж",
                            LastName = "Дёгурешафф"
                        });
                });

            modelBuilder.Entity("Models.Reception", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("MasterId")
                        .HasColumnType("int");

                    b.Property<int>("ServiceId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Time")
                        .HasColumnType("datetime2")
                        .HasColumnName("Время записи");

                    b.HasKey("Id");

                    b.HasIndex("ServiceId");

                    b.HasIndex("MasterId", "Time")
                        .IsUnique();

                    b.ToTable("Receptions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            MasterId = 1,
                            ServiceId = 1,
                            Time = new DateTime(2138, 12, 1, 23, 59, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            MasterId = 2,
                            ServiceId = 2,
                            Time = new DateTime(2138, 12, 2, 23, 59, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            MasterId = 3,
                            ServiceId = 3,
                            Time = new DateTime(2138, 12, 3, 23, 59, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("Models.Service", b =>
                {
                    b.Property<int>("ServiceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ServiceId"));

                    b.Property<string>("Description")
                        .HasMaxLength(1500)
                        .HasColumnType("nvarchar(1500)")
                        .HasColumnName("Описание");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Название");

                    b.Property<decimal>("Price")
                        .HasMaxLength(10)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("Цена");

                    b.HasKey("ServiceId");

                    b.ToTable("Services");

                    b.HasData(
                        new
                        {
                            ServiceId = 1,
                            Description = "по умолчанию 1",
                            Name = "Стрижка",
                            Price = 1000m
                        },
                        new
                        {
                            ServiceId = 2,
                            Description = "по умолчанию 2",
                            Name = "Окрашивание",
                            Price = 2000m
                        },
                        new
                        {
                            ServiceId = 3,
                            Description = "по умолчанию 3",
                            Name = "Восстановление",
                            Price = 3000m
                        });
                });

            modelBuilder.Entity("Models.Reception", b =>
                {
                    b.HasOne("Models.Master", "Master")
                        .WithMany("Receptions")
                        .HasForeignKey("MasterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Models.Service", "Service")
                        .WithMany("Receptions")
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Master");

                    b.Navigation("Service");
                });

            modelBuilder.Entity("Models.Master", b =>
                {
                    b.Navigation("Receptions");
                });

            modelBuilder.Entity("Models.Service", b =>
                {
                    b.Navigation("Receptions");
                });
#pragma warning restore 612, 618
        }
    }
}
